# Generated by Django 4.2 on 2023-04-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_rename_carga_horario_evento_carga_horaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='car_secundaria',
            new_name='cor_secundaria',
        ),
    ]
