# Generated by Django 4.2 on 2023-04-14 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0004_rename_car_secundaria_evento_cor_secundaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='evento_participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
